apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
      - name: mobile
        image: docker.io/YOUR_DOCKER_USERNAME/projet_asd-my-app-mob:latest
        ports:
        - containerPort: 19000
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-service
spec:
  selector:
    app: mobile
  ports:
    - protocol: TCP
      port: 19000
      targetPort: 19000
  type: LoadBalancer
