name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sampledb
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and run tests for API
        working-directory: ./api
        run: |
          npm install
          npm test

      - name: Install dependencies and run tests for web app
        working-directory: ./my-app-web
        run: |
          npm install
          npm test

      - name: Install dependencies and run tests for mobile app
        working-directory: ./my-app-mob
        run: |
          npm install
          npm test

  deploy:
    runs-on: self-hosted
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy API to Docker
        run: |
          docker-compose -f docker-compose.yml up -d --build api

      - name: Deploy Web App to Docker
        run: |
          docker-compose -f docker-compose.yml up -d --build my-app-web

      - name: Deploy Mobile App
        run: |
          echo "Deploy Mobile App step here"
